on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            env:
                description: 'The environment to deploy to (e.g., dev, prod)'
                required: true
                default: 'dev'

permissions:
    id-token: write
    contents: read

jobs:
    validate-and-plan:
        name: Validate Terraform
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.env || 'dev' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Google Cloud credentials
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}


            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_wrapper: false

            - name: Terraform Init
              run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="prefix=terraform/state/${{ github.event.inputs.env }}"

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: |
                terraform plan -out=plan-${{ github.event.inputs.env }}.tfplan \
                  -var="project=${{ secrets.GCP_PROJECT_ID }}" \
                  -var="region=${{ secrets.GCP_REGION }}" \
                  -var="state_bucket=${{ secrets.TF_STATE_BUCKET }}-${{ github.events.inputs.env }}" \
                  -var="env=${{ github.event.inputs.env }}"


    apply:
        name: Apply Terraform
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        needs: validate-and-plan
        environment:
            name: ${{ github.event.inputs.env || 'dev' }}  # Use the environment specified in the workflow_dispatch input
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Google Cloud credentials
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY }}
                  project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Install Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                  terraform_wrapper: false

            - name: Terraform Init
              run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="prefix=terraform/state/${{ github.event.inputs.env }}"

            - name: Terraform Apply
              run: terraform apply -auto-approve plan-${{ github.event.inputs.env }}.tfplan
